name: Build, Test and Release

on:
  push:
    branches: [master,main]
    tags: [v*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set PSModulePath
      shell: pwsh
      run: |
        $PSModulePath = @(
          [System.IO.Path]::Combine($Env:GITHUB_WORKSPACE, 'TMP', 'Modules'),
          $Env:PSModulePath
        ) -join [System.IO.Path]::PathSeparator
        "PSModulePath=$PSModulePath" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

    - name: Update PowerShell from LTS
      shell: pwsh
      run: |
        # Most of the code is from https://aka.ms/install-powershell.ps1 but adapted for GITHUB_PATH
        $Destination = "~/.powershell"
        if (-not (Test-Path -Path $Destination)) { New-Item -ItemType Directory -Path $Destination }

        Invoke-Expression "& { $(irm https://aka.ms/install-powershell.ps1) } -Destination $Destination"
        $TargetPath = Join-Path -Path $Destination -ChildPath "pwsh"
        $Symlink = "/usr/bin/pwsh"

        $Uid = id -u
        if ($Uid -ne "0") { $SUDO = "sudo" } else { $SUDO = "" }

        Write-Verbose "Make symbolic link '$Symlink' point to '$TargetPath'..." -Verbose
        & $SUDO ln -fs $TargetPath $Symlink

        if ($LASTEXITCODE -ne 0) {
            throw "Could not add to GITHUB_PATH: failed to make '$Symlink' point to '$TargetPath'."
        }

    - name: Setup.NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.14
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.14

    - name: Check version
      shell: pwsh
      run: |
        $PSVersionTable

    - name: Check version
      shell: pwsh
      run: |
        $PSVersionTable